local_localization:
  ros__parameters:
    frequency: 15.0

    use_sim_time: true
    two_d_mode: true
    publish_tf: true

    base_link_frame: base_link
    world_frame: odom

    debug: false

    # Defaults to "robot_localization_debug.txt" if unspecified. Please specify the full path.
    debug_out_file: local_debug.txt

    odom0: /diff_drive_base_controller/odom
    odom0_config:
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
      ]

    imu0: imu/data
    imu0_config:
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ]
